name: Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Zip file
        run: |
          mkdir picukiswitch-v0.2
          cp background.js manifest.json popup.html style.css picukiswitch-v0.2/
          cp -r icons/ picukiswitch-v0.2/
          zip -r picukiswitch-v0.2.zip picukiswitch-v0.2

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: picukiswitch-v0.2
          path: picukiswitch-v0.2.zip
