name: Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Zip file
        run: |
          mkdir files_to_zip
          cp background.js manifest.json popup.html style.css files_to_zip/
          cp icons/ files_to_zip/
          zip -r picukiswitch-v0.1.zip files_to_zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: picukiswitch-v0.1
          path: picukiswitch-v0.1.zip
