name: Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zip file
        run: |
          mkdir picukiswitch-v0.3
          cp background.js manifest.json popup.html style.css picukiswitch-v0.3/
          cp -r icons/ picukiswitch-v0.3/
          zip -r picukiswitch-v0.3.zip picukiswitch-v0.3

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          node-version: '16'
          name: picukiswitch-v0.3
          path: picukiswitch-v0.3.zip
