name: Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Zip file
        run: |
          mkdir picukiswitch-v0.1
          cp background.js manifest.json popup.html style.css picukiswitch-v0.1/
          cp -r icons/ picukiswitch-v0.1/
          zip -r picukiswitch-v0.1.zip picukiswitch-v0.1

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: picukiswitch-v0.1
          path: picukiswitch-v0.1.zip
